# Generated by Django 4.1.2 on 2023-08-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscalculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscalculation',
            name='hidden_cost',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Скрытый расход'),
        ),
    ]
