# Generated by Django 4.1.2 on 2023-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_passport_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
