# Generated by Django 4.1.2 on 2023-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_contract_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='date',
        ),
        migrations.AddField(
            model_name='contract',
            name='date_contract',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
