# Generated by Django 4.1.2 on 2023-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
