# Generated by Django 4.1.2 on 2023-07-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_client_passport_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportdetails',
            name='number',
        ),
        migrations.RemoveField(
            model_name='passportdetails',
            name='series',
        ),
        migrations.AddField(
            model_name='passportdetails',
            name='series_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия и номер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cost',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс доставки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deposit',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Задаток'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='finish_cost',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Окончательная стоимость'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='passport_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.passportdetails', verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
        migrations.AlterField(
            model_name='passportdetails',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прописка'),
        ),
        migrations.AlterField(
            model_name='passportdetails',
            name='issued_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='passportdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='passportdetails',
            name='personal_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Личный номер'),
        ),
    ]
