from django.contrib import admin
from .models import *


admin.site.register(ConnectionProfile)
admin.site.register(MountingMaterialsName)
admin.site.register(Article)
admin.site.register(ConnectionProfileName)
admin.site.register(ColorInside)
admin.site.register(ColorOutside)
admin.site.register(SealantOutside)
admin.site.register(SealantInside)
admin.site.register(SealantShtapik)
admin.site.register(Cylinder)
admin.site.register(ArticleAdditionalProfile)
admin.site.register(AdditionalProfile)
admin.site.register(ProductTypeDoor)
admin.site.register(ProfileDoor)
admin.site.register(Gorbylki)
admin.site.register(Handles)
# admin.site.register(TypeLamination)
# admin.site.register(TypeLamination2)
admin.site.register(SealInternal)
admin.site.register(SealOutside)
# admin.site.register(SealBasic)
admin.site.register(Opening)
admin.site.register(Lock)
admin.site.register(DoorHandles)
admin.site.register(DoorHinges)
# admin.site.register(Cylinder)
admin.site.register(DoorCloser)
admin.site.register(OpeningLimiter)
admin.site.register(Profile)
admin.site.register(Fittings)
admin.site.register(ProductType)
admin.site.register(Door)
admin.site.register(Lamination)
admin.site.register(Aggregate)
# admin.site.register(SealOutside)
# admin.site.register(SealInternal)
admin.site.register(TypeLamination)
admin.site.register(TypeLamination2)
admin.site.register(Sealant)
admin.site.register(SealBasic)
admin.site.register(SealRebate)
admin.site.register(SealantColor)
admin.site.register(Shpros)
admin.site.register(Shtapik)
admin.site.register(Sash)
admin.site.register(LaminationOutside)
admin.site.register(LaminationInside)
admin.site.register(ProfileWeight)
admin.site.register(Note)
admin.site.register(OtherComplectation)


# EXTRAWORKS
admin.site.register(ProductsInstall)
admin.site.register(PvcSlopes)
admin.site.register(FreePositions)

# EXTRAMATERIALS

# admin.site.register(FavoritePositions)

admin.site.register(Windowsill)
admin.site.register(WindowsillProvider)
admin.site.register(WindowsillColor)
admin.site.register(WindowsillPlug)
admin.site.register(WindowsillWidth)
admin.site.register(WindowsillConnection)
admin.site.register(WindowsillInstallation)
admin.site.register(WindowsillColorProvider)

admin.site.register(Flashing)
admin.site.register(FlashingProvider)
admin.site.register(FlashingColor)
admin.site.register(FlashingInstallation)

admin.site.register(Visors)
admin.site.register(VisorsProvider)
admin.site.register(VisorsColor)
admin.site.register(VisorsInstallation)

admin.site.register(Casing)
admin.site.register(CasingPrice)
admin.site.register(CasingNipelPrice)
admin.site.register(CasingProvider)

admin.site.register(CasingColor)
admin.site.register(CasingInstallation)
admin.site.register(CasingFastening)

admin.site.register(LowTides)
admin.site.register(LowTidesType)
admin.site.register(LowTidesProvider)
admin.site.register(LowTidesColor)
admin.site.register(LowTidesInstallation)

admin.site.register(SlopesOfMetal)
admin.site.register(SlopesOfMetalProvider)
admin.site.register(SlopesOfMetalColor)
admin.site.register(SlopesOfMetalInstallation)

admin.site.register(InternalSlope)
admin.site.register(InternalSlopeProvider)
admin.site.register(InternalSlopeColor)
admin.site.register(InternalSlopeInstallation)


admin.site.register(Works)
admin.site.register(ProviderWindow)
