# Generated by Django 4.1.2 on 2023-08-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visorscalcmob',
            name='width_1',
            field=models.IntegerField(default=0, verbose_name='Ширина 1'),
        ),
        migrations.AddField(
            model_name='visorscalcmob',
            name='width_2',
            field=models.IntegerField(default=0, verbose_name='Ширина 2'),
        ),
        migrations.AddField(
            model_name='visorscalcmob',
            name='width_3',
            field=models.IntegerField(default=0, verbose_name='Ширина 3'),
        ),
    ]
