# Generated by Django 4.1.2 on 2023-08-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowdiscountmarkups',
            name='markups_6',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №6'),
        ),
        migrations.AddField(
            model_name='windowdiscountmarkups',
            name='markups_6_in_percent',
            field=models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №6 )'),
        ),
        migrations.AddField(
            model_name='windowdiscountmarkups',
            name='markups_7',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №7'),
        ),
        migrations.AddField(
            model_name='windowdiscountmarkups',
            name='markups_7_in_percent',
            field=models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №7 )'),
        ),
        migrations.AlterField(
            model_name='windowdiscountmarkups',
            name='discount',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Значение скидки'),
        ),
        migrations.AlterField(
            model_name='windowdiscountmarkups',
            name='markups_diler',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №1'),
        ),
        migrations.AlterField(
            model_name='windowdiscountmarkups',
            name='markups_diler_in_percent',
            field=models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №1 )'),
        ),
        migrations.AlterField(
            model_name='windowdiscountmarkups',
            name='markups_retail',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №2'),
        ),
        migrations.AlterField(
            model_name='windowdiscountmarkups',
            name='markups_retail_in_percent',
            field=models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №2 )'),
        ),
    ]
