# Generated by Django 4.1.2 on 2023-08-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_windowsill_windowsill_connection_and_more'),
        ('calculation', '0002_windowdiscountmarkups_markups_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lowtidestype', verbose_name='Тип отлива'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='width_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина 1'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='width_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина 2'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='width_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина 3'),
        ),
    ]
