# Generated by Django 4.1.2 on 2023-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_lowtidescalc_low_tides_type_lowtidescalc_width_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visorscalc',
            name='width_1',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Ширина 1'),
        ),
        migrations.AddField(
            model_name='visorscalc',
            name='width_2',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Ширина 2'),
        ),
        migrations.AddField(
            model_name='visorscalc',
            name='width_3',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Ширина 3'),
        ),
    ]
