# Generated by Django 4.1.2 on 2023-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_visorscalc_width_1_visorscalc_width_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casingcalc',
            name='nipel_count',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Количество Нипелей'),
        ),
    ]
