# Generated by Django 4.1.2 on 2023-07-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProfileLamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ламинация')),
            ],
            options={
                'verbose_name': 'Ламинация доборного профиль',
                'verbose_name_plural': 'Ламинация доборных профилей',
            },
        ),
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заполнитель №1')),
            ],
            options={
                'verbose_name': 'Заполнитель №1',
                'verbose_name_plural': 'Заполнитель №1',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Артикуль',
                'verbose_name_plural': 'Артикули',
            },
        ),
        migrations.CreateModel(
            name='ArticleAdditionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Артикуль доб. профиля',
                'verbose_name_plural': 'Артикуль доб. профиля',
            },
        ),
        migrations.CreateModel(
            name='CasingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет наличника',
                'verbose_name_plural': 'Цвета наличников',
            },
        ),
        migrations.CreateModel(
            name='CasingFastening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название крепление')),
            ],
            options={
                'verbose_name': 'Крепление наличника',
                'verbose_name_plural': 'Крепления наличников',
            },
        ),
        migrations.CreateModel(
            name='CasingInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж наличника',
                'verbose_name_plural': 'Монтажи наличников',
            },
        ),
        migrations.CreateModel(
            name='CasingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик наличников',
                'verbose_name_plural': 'Поставщики наличников',
            },
        ),
        migrations.CreateModel(
            name='ColorInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет внутри')),
            ],
            options={
                'verbose_name': 'Цвет внутри',
                'verbose_name_plural': 'Цвета внутри',
            },
        ),
        migrations.CreateModel(
            name='ColorOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет снаружи')),
            ],
            options={
                'verbose_name': 'Цвет снаружи',
                'verbose_name_plural': 'Цвета снаружи',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название соед.профиля')),
            ],
            options={
                'verbose_name': 'Название соед.профиля',
                'verbose_name_plural': 'Название соед.профиля',
            },
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цилиндр')),
            ],
            options={
                'verbose_name': 'Цилиндр',
                'verbose_name_plural': 'Цилиндры',
            },
        ),
        migrations.CreateModel(
            name='DoorCloser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доводчик')),
            ],
            options={
                'verbose_name': 'Доводчик',
                'verbose_name_plural': 'Доводчики',
            },
        ),
        migrations.CreateModel(
            name='DoorHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверная ручки')),
            ],
            options={
                'verbose_name': 'Дверная ручка',
                'verbose_name_plural': 'Дверные ручки',
            },
        ),
        migrations.CreateModel(
            name='DoorHinges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверные петли')),
            ],
            options={
                'verbose_name': 'Дверные петли',
                'verbose_name_plural': 'Дверные петли',
            },
        ),
        migrations.CreateModel(
            name='Fittings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фурнитура')),
            ],
            options={
                'verbose_name': 'Фурнитура',
                'verbose_name_plural': 'Фурнитуры',
            },
        ),
        migrations.CreateModel(
            name='FlashingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет нащельника',
                'verbose_name_plural': 'Цвета нащельников',
            },
        ),
        migrations.CreateModel(
            name='FlashingInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж нащельника',
                'verbose_name_plural': 'Монтажи нащельников',
            },
        ),
        migrations.CreateModel(
            name='FlashingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик нащельников',
                'verbose_name_plural': 'Поставщики нащельников',
            },
        ),
        migrations.CreateModel(
            name='FreePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бесплатные позиции')),
            ],
            options={
                'verbose_name': 'Бесплатные позиции',
                'verbose_name_plural': 'Бесплатные позиции',
            },
        ),
        migrations.CreateModel(
            name='Gorbylki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Горбыльки')),
            ],
            options={
                'verbose_name': 'Горбыльки',
                'verbose_name_plural': 'Горбыльки',
            },
        ),
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ручка')),
            ],
            options={
                'verbose_name': 'Ручка',
                'verbose_name_plural': 'Ручки',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет внутренних откосов',
                'verbose_name_plural': 'Цвета внутренних откосов',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж внутренних откосов',
                'verbose_name_plural': 'Монтажи внутренних откосов',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик внутренние откосы',
                'verbose_name_plural': 'Поставщики внутренние откосы',
            },
        ),
        migrations.CreateModel(
            name='LaminationInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ланиманция внутри')),
            ],
            options={
                'verbose_name': 'Ланиманция внутри',
                'verbose_name_plural': 'Ланиманция внутри',
            },
        ),
        migrations.CreateModel(
            name='LaminationOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ламинация снаружи')),
            ],
            options={
                'verbose_name': 'Ламинация снаружи',
                'verbose_name_plural': 'Ламинация снаружи',
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверной замок')),
            ],
            options={
                'verbose_name': 'Дверной замок',
                'verbose_name_plural': 'Дверные замки',
            },
        ),
        migrations.CreateModel(
            name='LowTidesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет отлива',
                'verbose_name_plural': 'Цвета отливов',
            },
        ),
        migrations.CreateModel(
            name='LowTidesConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Соединитель отлива',
                'verbose_name_plural': 'Соединители отливов',
            },
        ),
        migrations.CreateModel(
            name='LowTidesInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж отлива',
                'verbose_name_plural': 'Монтажи отливов',
            },
        ),
        migrations.CreateModel(
            name='LowTidesPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Заглушка отлива',
                'verbose_name_plural': 'Заглушки отливов',
            },
        ),
        migrations.CreateModel(
            name='LowTidesProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик отливов',
                'verbose_name_plural': 'Поставщики отливов',
            },
        ),
        migrations.CreateModel(
            name='LowTidesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип Отлива',
                'verbose_name_plural': 'Типы отливов',
            },
        ),
        migrations.CreateModel(
            name='MountingMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Монтажные материалы',
                'verbose_name_plural': 'Монтажные материалы',
            },
        ),
        migrations.CreateModel(
            name='MountingMaterialsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование монтажных материалов')),
            ],
            options={
                'verbose_name': 'Монтажные материалы',
                'verbose_name_plural': 'Монтажные материалы',
            },
        ),
        migrations.CreateModel(
            name='MountingMaterialsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик материалов',
                'verbose_name_plural': 'Поставщики материалов',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Примечание',
                'verbose_name_plural': 'Примечание',
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Открывание')),
            ],
            options={
                'verbose_name': 'Открывание',
                'verbose_name_plural': 'Открывания',
            },
        ),
        migrations.CreateModel(
            name='OpeningLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ограничитель открывания')),
            ],
            options={
                'verbose_name': 'Ограничитель открывания',
                'verbose_name_plural': 'Ограничители открывания',
            },
        ),
        migrations.CreateModel(
            name='OtherComplectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прочее комплектующие')),
            ],
            options={
                'verbose_name': 'Прочее комплектующие',
                'verbose_name_plural': 'Прочее комплектующие',
            },
        ),
        migrations.CreateModel(
            name='ProductsInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Монтаж изделий')),
            ],
            options={
                'verbose_name': 'Монтаж изделий',
                'verbose_name_plural': 'Монтаж изделий',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Тип изделия',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия двери',
                'verbose_name_plural': 'Тип изделия двери',
            },
        ),
        migrations.CreateModel(
            name='ProfileWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Масса профиля')),
            ],
            options={
                'verbose_name': 'Масса профиля',
                'verbose_name_plural': 'Масса профиля',
            },
        ),
        migrations.CreateModel(
            name='ProviderWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик профиля',
                'verbose_name_plural': 'Поставщики профилей',
            },
        ),
        migrations.CreateModel(
            name='PvcSlopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Откосы ПВХ')),
            ],
            options={
                'verbose_name': 'Откосы ПВХ',
                'verbose_name_plural': 'Откосы ПВХ',
            },
        ),
        migrations.CreateModel(
            name='Sash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Створка')),
            ],
            options={
                'verbose_name': 'Створка',
                'verbose_name_plural': 'Створки',
            },
        ),
        migrations.CreateModel(
            name='SealantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет уплотнения')),
            ],
            options={
                'verbose_name': 'Цвет уплотнения',
                'verbose_name_plural': 'Цвет уплотнения',
            },
        ),
        migrations.CreateModel(
            name='SealantInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение внутри')),
            ],
            options={
                'verbose_name': 'Исполнение внутри уплотнителя',
                'verbose_name_plural': 'Исполнение внутрии уплотнителя',
            },
        ),
        migrations.CreateModel(
            name='SealantOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение снаружи')),
            ],
            options={
                'verbose_name': 'Исполнение снаружи уплотнителя',
                'verbose_name_plural': 'Исполнение снаружи уплотнителя',
            },
        ),
        migrations.CreateModel(
            name='SealantShtapik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уплотнитель')),
            ],
            options={
                'verbose_name': 'Уплотнитель ( штапик )',
                'verbose_name_plural': 'Уплотнитель ( штапики ) ',
            },
        ),
        migrations.CreateModel(
            name='SealBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение основы детали')),
            ],
            options={
                'verbose_name': 'Исполнение основы детали',
                'verbose_name_plural': 'Исполнение основы детали',
            },
        ),
        migrations.CreateModel(
            name='SealInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение внутри')),
            ],
            options={
                'verbose_name': 'Исполнение внутри',
                'verbose_name_plural': 'Исполнение внутри',
            },
        ),
        migrations.CreateModel(
            name='SealOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение снаружи')),
            ],
            options={
                'verbose_name': 'Исполнение снаружи',
                'verbose_name_plural': 'Исполнение снаружи',
            },
        ),
        migrations.CreateModel(
            name='SealRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уплотнение притвора')),
            ],
            options={
                'verbose_name': 'Уплотнение притвора',
                'verbose_name_plural': 'Уплотнение притвора',
            },
        ),
        migrations.CreateModel(
            name='Shpros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Шпрос')),
            ],
            options={
                'verbose_name': 'Шпрос',
                'verbose_name_plural': 'Шпросы',
            },
        ),
        migrations.CreateModel(
            name='Shtapik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Штапик')),
            ],
            options={
                'verbose_name': 'Штапик',
                'verbose_name_plural': 'Штапики',
            },
        ),
        migrations.CreateModel(
            name='SlopesOfMetalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет откосов из металла',
                'verbose_name_plural': 'Цвета откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='SlopesOfMetalInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж откосов из металла',
                'verbose_name_plural': 'Монтажи откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='SlopesOfMetalProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик откосов из металла',
                'verbose_name_plural': 'Поставщики откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='TypeLamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип ламинации')),
            ],
            options={
                'verbose_name': 'Тип ламинации',
                'verbose_name_plural': 'Типы ламинации',
            },
        ),
        migrations.CreateModel(
            name='TypeLamination2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид ламинации')),
            ],
            options={
                'verbose_name': 'Вид ламинации',
                'verbose_name_plural': 'Виды ламинации',
            },
        ),
        migrations.CreateModel(
            name='VisorsColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет козырька',
                'verbose_name_plural': 'Цвета козырьков',
            },
        ),
        migrations.CreateModel(
            name='VisorsInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж козырька',
                'verbose_name_plural': 'Монтажи козырьков',
            },
        ),
        migrations.CreateModel(
            name='VisorsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик козырьков',
                'verbose_name_plural': 'Поставщики козырьков',
            },
        ),
        migrations.CreateModel(
            name='WindowsillColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет подоконника',
                'verbose_name_plural': 'Цвета подоконников',
            },
        ),
        migrations.CreateModel(
            name='WindowsillConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Соединитель подоконника',
                'verbose_name_plural': 'Соединители подоконников',
            },
        ),
        migrations.CreateModel(
            name='WindowsillInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж подоконника',
                'verbose_name_plural': 'Монтажи подоконников',
            },
        ),
        migrations.CreateModel(
            name='WindowsillPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Заглушка подоконника',
                'verbose_name_plural': 'Заглушки подоконников',
            },
        ),
        migrations.CreateModel(
            name='WindowsillProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик подоконников',
                'verbose_name_plural': 'Поставщики подоконников',
            },
        ),
        migrations.CreateModel(
            name='WindowsillWidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полка подоконника')),
            ],
            options={
                'verbose_name': 'Полка подоконника',
                'verbose_name_plural': 'Полки подоконников',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование работы')),
                ('price', models.FloatField(default=0.0, max_length=255, verbose_name='Цена работы')),
            ],
            options={
                'verbose_name': 'Работы',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Windowsill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подоконника')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип подоконника')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('windowsill_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.windowsillprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Подоконник',
                'verbose_name_plural': 'Подоконники',
            },
        ),
        migrations.CreateModel(
            name='Visors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Развертка козырька')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('visors_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.visorsprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Козырек',
                'verbose_name_plural': 'Козырьки',
            },
        ),
        migrations.CreateModel(
            name='SlopesOfMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип откосов из металла')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('slopes_of_metal_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.slopesofmetalprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Откосы из металла',
                'verbose_name_plural': 'откосы из металла',
            },
        ),
        migrations.CreateModel(
            name='Sealant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sealant_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantcolor', verbose_name='Цвет уплотнителя')),
                ('sealant_inside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantinside', verbose_name='Исполнение снаружи')),
                ('sealant_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantoutside', verbose_name='Исполнение внутри')),
                ('sealant_shtapik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantshtapik', verbose_name='Штапик')),
            ],
            options={
                'verbose_name': 'Уплотнитель',
                'verbose_name_plural': 'Уплотнители',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профиль')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Прямой'), (1, 'Фигурный')], null=True, verbose_name='type')),
                ('provider_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.providerwindow', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиля',
            },
        ),
        migrations.CreateModel(
            name='MountingMaterialsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип монтажных материалов')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('mounting_materials_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.mountingmaterialsprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Тип монтажного материала',
                'verbose_name_plural': 'Типы монтажных материалов',
            },
        ),
        migrations.CreateModel(
            name='LowTides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отлива')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('low_tides_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lowtidesprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Отлив',
                'verbose_name_plural': 'Отливы',
            },
        ),
        migrations.CreateModel(
            name='Lamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealbasic', verbose_name='Исполнение основы детали')),
                ('seal_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealinternal', verbose_name='Исполнение внутри')),
                ('seal_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealoutside', verbose_name='Исполнение снаружи')),
                ('type_lamination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.typelamination', verbose_name='Тип ламинации')),
                ('type_lamination1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.typelamination2', verbose_name='Вид ламинации')),
            ],
            options={
                'verbose_name': 'Ламинация',
                'verbose_name_plural': 'Ламинации',
            },
        ),
        migrations.CreateModel(
            name='InternalSlope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип внутренних откосов')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование внутренних откосов')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('internal_slope_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopeprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Внутренние откосы',
                'verbose_name_plural': 'Внутренние откосы',
            },
        ),
        migrations.CreateModel(
            name='Flashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название нащельника')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('flashing_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashingprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Нащельник',
                'verbose_name_plural': 'Нащельники',
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shtulp', models.BooleanField(blank=True, default=False, verbose_name='Со штульпом')),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.cylinder', verbose_name='Цилиндр')),
                ('door_closer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorcloser', verbose_name='Доводчик')),
                ('door_hinges', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorhinges', verbose_name='Дверные петли')),
                ('handle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorhandles', verbose_name='Дверные ручки')),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lock', verbose_name='Замок')),
                ('opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.opening', verbose_name='Открывание')),
                ('opening_limiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.openinglimiter', verbose_name='Ограничитель открывания')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.producttypedoor', verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Дверь',
                'verbose_name_plural': 'Двери',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Длина')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена')),
                ('color_inside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.colorinside', verbose_name='Цвет внутри')),
                ('color_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.coloroutside', verbose_name='Цвет снаружи')),
                ('connection_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.article', verbose_name='Артикуль')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofilename', verbose_name='Название соен.профиля')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Соединительные профиля',
                'verbose_name_plural': 'Соединительные профиля',
            },
        ),
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название наличника')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('casing_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.casingprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Наличник',
                'verbose_name_plural': 'Наличники',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ширина')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена')),
                ('additional_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.articleadditionalprofile', verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Доборный профиль',
                'verbose_name_plural': 'Доборные профиля',
            },
        ),
    ]
