# Generated by Django 4.1.2 on 2023-08-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_rename_price_in_byn_lowtidesconnection_price_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='aggregate',
            name='camera',
            field=models.IntegerField(choices=[(1, '1-ух камерный'), (2, '2-ух камерный')], default=1, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='aggregate',
            name='ramka',
            field=models.IntegerField(choices=[(1, 'Стандарт'), (2, 'Черная'), (2, 'Белая')], default=1, verbose_name='Рамка'),
        ),
    ]
