# Generated by Django 4.1.2 on 2023-08-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_aggregate_type_alter_aggregate_ramka'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профиль')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Прямой'), (1, 'Фигурный')], null=True, verbose_name='type')),
                ('provider_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.providerwindow', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Профиль дверной',
                'verbose_name_plural': 'Профиля дверные',
            },
        ),
        migrations.AddField(
            model_name='door',
            name='profile_door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.profiledoor', verbose_name='Дверной профиль'),
        ),
    ]
