# Generated by Django 4.1.2 on 2023-08-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_windowsillcolorprovider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregate',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sendwich'), (2, 'Энергосберегающие'), (3, 'EnergyAir'), (4, 'Тонированные'), (5, 'Фениксы'), (6, 'Феникс клер'), (7, 'Феникс бронза'), (8, 'Феникс грей'), (9, 'CRYSTALVISION'), (10, 'Антирезонансные'), (11, 'Антивандальные'), (12, 'Триплекс'), (13, 'Простые')], default=1, verbose_name='Тип'),
        ),
    ]
