# Generated by Django 4.1.2 on 2023-08-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_alter_aggregate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsillcolor',
            name='windowsill_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.windowsillprovider', verbose_name='Поставщик'),
        ),
    ]
