# Generated by Django 4.1.2 on 2023-08-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_alter_windowsillcolor_windowsill_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='casingcolor',
            name='casing_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.casingprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='flashingcolor',
            name='flashing_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashingprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='internalslopeinstallation',
            name='internal_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopeprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='lowtidescolor',
            name='low_tides_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lowtidesprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='slopesofmetalinstallation',
            name='slopes_of_metal_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.slopesofmetalprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='visorscolor',
            name='visors_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.visorsprovider', verbose_name='Поставщик'),
        ),
    ]
