# Generated by Django 4.1.2 on 2023-08-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0009_casingcolor_casing_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsillplug',
            name='windowsill_plug_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.windowsillprovider', verbose_name='Поставщик'),
        ),
    ]
