# Generated by Django 4.1.2 on 2023-08-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0010_windowsillplug_windowsill_plug_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsill',
            name='windowsill_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_windowsills', to='constructor.windowsillconnection', verbose_name='Соединитель'),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='windowsill_plug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug_windowsills', to='constructor.windowsillplug', verbose_name='Заглушка'),
        ),
    ]
