# Generated by Django 4.1.2 on 2023-08-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0012_remove_casing_price_input_casingprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casingprice',
            options={'verbose_name': 'Наличник цены', 'verbose_name_plural': 'Наличники цены'},
        ),
        migrations.RemoveField(
            model_name='casingprice',
            name='name',
        ),
    ]
