# Generated by Django 4.1.2 on 2023-08-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0013_alter_casingprice_options_remove_casingprice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashing',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Металл'), (1, 'Пластик')], null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='flashing',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профиль'),
        ),
    ]
