# Generated by Django 4.1.2 on 2023-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0014_flashing_type_alter_flashing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashing',
            name='width',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ширина'),
        ),
    ]
