# Generated by Django 4.1.2 on 2023-08-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0015_flashing_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casingprice',
            name='width_1',
        ),
        migrations.RemoveField(
            model_name='casingprice',
            name='width_2',
        ),
        migrations.AddField(
            model_name='casingprice',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина'),
        ),
        migrations.CreateModel(
            name='CasingNipelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('casing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.casing', verbose_name='Наличник')),
                ('casing_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.casingprovider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Нипели для  наличников',
                'verbose_name_plural': 'Непили для наличников ',
            },
        ),
    ]
