# Generated by Django 4.1.2 on 2023-08-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0016_remove_casingprice_width_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casingnipelprice',
            options={'verbose_name': 'Нипели для наличников', 'verbose_name_plural': 'Нипели для наличников '},
        ),
    ]
